# Generated by Django 3.1.7 on 2021-04-20 16:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 16, 42, 26, 694049, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 16, 42, 26, 692908, tzinfo=utc)),
        ),
    ]
