# Generated by Django 3.2 on 2021-04-20 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210420_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='create_date',
        ),
        migrations.AlterField(
            model_name='comments',
            name='Create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 17, 47, 31, 145437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 17, 47, 31, 145437, tzinfo=utc)),
        ),
    ]
