# Generated by Django 3.2 on 2021-04-20 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210420_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 18, 13, 17, 498283, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 18, 13, 17, 498283, tzinfo=utc)),
        ),
    ]
